CREATE ROLE HANA_CLEANING;
GRANT BACKUP ADMIN, CATALOG READ, LOG ADMIN, MONITOR ADMIN, RESOURCE ADMIN, TRACE ADMIN to HANA_CLEANING;
GRANT SELECT, DELETE ON "_SYS_STATISTICS"."HOST_OBJECT_LOCK_STATISTICS_BASE" TO HANA_CLEANING; 
GRANT SELECT, DELETE ON "_SYS_STATISTICS"."STATISTICS_ALERTS_BASE" TO HANA_CLEANING; 
GRANT SELECT, DELETE ON "_SYS_REPO"."OBJECT_HISTORY" TO HANA_CLEANING; 
CREATE USER HANACLEANER1 password <your password for HANACLEANER1 DB USER>;
GRANT HANA_CLEANING to HANACLEANER1;
ALTER USER HANACLEANER1 DISABLE PASSWORD LIFETIME;